c_roads:
  r: 0.8
  g: 0.2
  b: 0.2
  a: 0.8

c_buildings:
  r: 0.0
  g: 0.3
  b: 0.7
  a: 0.8

c_rails:
  r: 0.0
  g: 0.7
  b: 0.7
  a: 0.8

c_footways:
  r: 0.85
  g: 1.0
  b: 0.85
  a: 0.5

c_water:
  r: 0.0
  g: 0.0
  b: 1.0
  a: 0.5

c_forest:
  r: 0.2
  g: 1.0
  b: 0.3
  a: 0.5

c_antiforest:
  r: 0.4
  g: 0.0
  b: 0.4
  a: 0.5

c_agriculture:
  r: 0.3
  g: 0.7
  b: 0.7
  a: 0.5

c_untraversable:
  r: 0.6
  g: 0.0
  b: 0.3
  a: 0.5

c_traversable:
  r: 0.2
  g: 0.6
  b: 0.4
  a: 0.5

c_obstacles:
  r: 1.0
  g: 0.6
  b: 0.6
  a: 0.5